src/Entity/Orders.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OrdersRepository")
 */
class Orders
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $userid;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $amount;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $adress;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $phone;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $shipinfo;

    /**
     * @ORM\Column(type="string", length=20, nullable=true)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $note;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $updated_at;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserid(): ?int
    {
        return $this->userid;
    }

    public function setUserid(?int $userid): self
    {
        $this->userid = $userid;

        return $this;
    }

    public function getAmount(): ?int
    {
        return $this->amount;
    }

    public function setAmount(?int $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): self
    {
        $this->adress = $adress;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(?string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): self
    {
        $this->phone = $phone;

        return $this;
    }

    public function getShipinfo(): ?string
    {
        return $this->shipinfo;
    }

    public function setShipinfo(?string $shipinfo): self
    {
        $this->shipinfo = $shipinfo;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

   public function setUpdatedAt(?\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

   public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

}

src/Form/OrdersType.php
<?php

namespace App\Form;

use App\Entity\Orders;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class OrdersType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('userid')
            ->add('amount')
            ->add('name')
            ->add('adress')
            ->add('city')
            ->add('phone')
            ->add('shipinfo')
            ->add('status', ChoiceType::class,[
                    'choices'=>[
                        'New'=>'New',
                        'Accepted'=>'Accepted',
                        'Kargoda'=>'Kargoda',
                        'Canceled'=>'Canceled',
                        'Completed'=>'Completed'
        ],
                ]
            )
            ->add('note')
            ->add('updated_at')
            ->add('created_at')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Orders::class,
        ]);
    }
}

src/Controller/Admin/OrdersController.php
<?php

namespace App\Controller\Admin;

use App\Entity\OrderDetail;
use App\Entity\Orders;
use App\Form\OrdersType;
use App\Repository\OrderDetailRepository;
use App\Repository\OrdersRepository;
use App\Repository\ShopcartRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/orders")
 */
class OrdersController extends AbstractController
{
    /**
     * @Route("/", name="admin_orders_index", methods={"GET"})
     */
    public function index(OrdersRepository $ordersRepository): Response
    {
        return $this->render('admin/orders/index.html.twig', [
            'orders' => $ordersRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="admin_orders_new", methods={"GET","POST"})
     */
    public function new(Request $request, ShopcartRepository $shopcartRepository): Response
    {
        $orders = new Orders();
        $form = $this->createForm(OrdersType::class, $orders);
        $form->handleRequest($request);

        $user = $this->getUser(); // Calling Login user data
        $userid = $user->getid();
        $total=$shopcartRepository->getUserShopCartTotal($userid); // Get total amount of user shopcart

        $submittedToken = $request->request->get('token'); // get csrf token information

        if ($this->isCsrfTokenValid('form-order', $submittedToken)) {
            if ($form->isSubmitted()) {
                // Kredi kartı bilgilerini ilgili banka servisine gönder
                // Onay gelirse kaydetmeye devam et yoksa order sayfasına hata gönder

                $em = $this->getDoctrine()->getManager();

                $orders->setUserid($userid);
                $orders->setAmount($total);
                $orders->setStatus("New");

                $em->persist($orders);
                $em->flush();

                $orderid = $orders->getId(); //  Get last insert orders data id

                $shopcart = $shopcartRepository->getAllShopcartUser($userid);

                foreach ($shopcart as $item) {

                    $orderdetail = new OrderDetail();
                    // Filling Orderdetails data from shopcart
                    $orderdetail->setOrderid($orderid);
                    $orderdetail->setUserid($user->getid()); // login user id
                    $orderdetail->setSiparisid($item["siparisid"]);
                    $orderdetail->setQuantity($item["quantity"]);
                    
                    $orderdetail->setName($item["title"]);
                    $orderdetail->setStatus("Ordered");

                    $em->persist($orderdetail);
                    $em->flush();

                }



                $this->addFlash('success', 'Siparişiniz Başarıyla Gerçekleştirilmiştir. Teşekkür Ederiz');
                return $this->redirectToRoute('admin_orders_index');
            }
        }

        return $this->render('admin/orders/new.html.twig', [
            'order' => $orders,
            'total' => $total,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}", name="admin_orders_show", methods={"GET"})
     */
    public function show(Orders $order,OrderDetailRepository $orderDetailRepository): Response
    {
        $user=$this->getUser();
        $userid=$user->getid();
        $orderid=$order->getId();
        $orderdetail=$orderDetailRepository->findBy(
            ['orderid'=>$orderid]
        );
        return $this->render('admin/orders/show.html.twig', [
            'order' => $order,
            'orderdetail'=>$orderdetail,

        ]);
    }

    /**
     * @Route("/{id}/edit", name="admin_orders_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Orders $order): Response
    {
        $form = $this->createForm(OrdersType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('admin_orders_index');
        }

        return $this->render('admin/orders/edit.html.twig', [
            'order' => $order,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="admin_orders_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Orders $order): Response
    {
        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('admin_orders_index');
    }

    private function createQuery(string $string)
    {
    }
    /**
     * @Route("/orders/{id}/update", name="admin_orders_update", methods="POST")
     */
    public function orders_update($id, Request $request, Orders $orders) : Response
    {
        $em = $this->getDoctrine()->getManager();
        $sql = "UPDATE orders SET shipinfo=:shipinfo,note=:note,status=:status WHERE id=:id";
        $statement = $em->getConnection()->prepare($sql);
        $statement->bindValue('shipinfo', $request->request->get('shipinfo'));
        $statement->bindValue('note', $request->request->get('note'));
        $statement->bindValue('status', $request->request->get('status'));
        $statement->bindValue('id', $id);
        $statement->execute();
        $this->addFlash('success', 'Siparis Bilgileri Güncellenmistir');

        return $this->redirectToRoute('admin_orders_show', array('id' => $id));
    }
}

src/Controller/OrdersController.php
<?php

namespace App\Controller;

use App\Entity\OrderDetail;
use App\Entity\Orders;
use App\Form\OrdersType;
use App\Repository\OrderDetailRepository;
use App\Repository\OrdersRepository;
use App\Repository\ShopcartRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/orders")
 */
class OrdersController extends AbstractController
{
    /**
     * @Route("/", name="orders_index", methods={"GET"})
     */
    public function index(OrdersRepository $ordersRepository): Response
    {
        return $this->render('orders/index.html.twig', [
            'orders' => $ordersRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="orders_new", methods={"GET","POST"})
     */
    public function new(Request $request, ShopcartRepository $shopcartRepository): Response
    {
        $orders = new Orders();
        $form = $this->createForm(OrdersType::class, $orders);
        $form->handleRequest($request);

        $user = $this->getUser(); // Calling Login user data
        $userid = $user->getid();
        $total=$shopcartRepository->getUserShopCartTotal($userid); // Get total amount of user shopcart

        $submittedToken = $request->request->get('token'); // get csrf token information

        if ($this->isCsrfTokenValid('form-order', $submittedToken)) {
            if ($form->isSubmitted()) {
                // Kredi kartı bilgilerini ilgili banka servisine gönder
                // Onay gelirse kaydetmeye devam et yoksa order sayfasına hata gönder

                $em = $this->getDoctrine()->getManager();

                $orders->setUserid($userid);
                $orders->setAmount($total);
                $orders->setStatus("New");

                $em->persist($orders);
                $em->flush();

                $orderid = $orders->getId(); //  Get last insert orders data id

                $shopcart = $shopcartRepository->getAllShopcartUser($userid);

                foreach ($shopcart as $item) {

                    $orderdetail = new OrderDetail();
                    // Filling Orderdetails data from shopcart
                    $orderdetail->setOrderid($orderid);
                    $orderdetail->setUserid($user->getid()); // login user id
                    $orderdetail->setSiparisid($item["siparisid"]);
                    $orderdetail->setQuantity($item["quantity"]);
                    
                    $orderdetail->setName($item["title"]);
                    $orderdetail->setStatus("Ordered");

                    $em->persist($orderdetail);
                    $em->flush();

                }



                $this->addFlash('success', 'Siparişiniz Başarıyla Gerçekleştirilmiştir. Teşekkür Ederiz');
                return $this->redirectToRoute('orders_index');
            }
        }

        return $this->render('orders/new.html.twig', [
            'order' => $orders,
            'total' => $total,
            'form' => $form->createView(),
        ]);
    }


    /**
     * @Route("/{id}", name="orders_show", methods={"GET"})
     */
    public function show(Orders $order,OrderDetailRepository $orderDetailRepository): Response
    {
        $user=$this->getUser();
        $userid=$user->getid();
        $orderid=$order->getId();
        $orderdetail=$orderDetailRepository->findBy(
            ['orderid'=>$orderid]
        );
        return $this->render('orders/show.html.twig', [
            'order' => $order,
            'orderdetail'=>$orderdetail,

        ]);
    }

    /**
     * @Route("/{id}/edit", name="orders_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Orders $order): Response
    {
        $form = $this->createForm(OrdersType::class, $order);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('orders_index');
        }

        return $this->render('orders/edit.html.twig', [
            'order' => $order,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="orders_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Orders $order): Response
    {
        if ($this->isCsrfTokenValid('delete'.$order->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($order);
            $entityManager->flush();
        }

        return $this->redirectToRoute('orders_index');
    }

    private function createQuery(string $string)
    {
    }


}

templates/orders/_delete_form.html.twig
<form method="post" action="{{ path('orders_delete', {'id': order.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ order.id) }}">
    <button class="btn">Delete</button>
</form>

templates/orders/_form.html.twig
{{ include('messages.html.twig') }}


<h2 class="title text-center">Adres ve Teslimat Bilgileri</h2>
<div class="status alert alert-success" style="display: none"></div>
<form id="main-contact-form" class="contact-form row" name="order"  action="{{ path('orders_new') }}" method="post">
    <label class="col-md-12 control-label">Ödenecek Tutar :</label>
    <div class="form-group col-md-8">
        <input type="text" name="orders[amount]" value=" TL" placeholder="name" class="form-control"/>
    </div>

    <div class="form-group col-md-12">
        <p>
            KARGO ALICI BİLGİLERİ:
        </p>
    </div>
    <label class="col-md-12 control-label">Adı Soyadı :</label>
    <div class="form-group col-md-8">
        <input type="text" name="orders[name]" class="form-control" required="required" placeholder="name" value="{{ app.user.name }} {{ app.user.surname }}">
    </div>
    <label class="col-md-12 control-label"> Adresi :</label>
    <div class="form-group col-sm-12">
        <textarea name="orders[adress]" class="form-control" required="required" placeholder="adress" value="{{ app.user.adress }}">{{ app.user.adress }}</textarea>
    </div>

    <label class="col-md-12 control-label"> Şehir :</label>
    <div class="form-group col-md-12">
        <input type="text" name="orders[city]" class="form-control" required="required" placeholder="city" value="{{ app.user.city }}">
    </div>
    <label class="col-md-12 control-label"> Telefon :</label>
    <div class="form-group col-md-12">
        <input type="text" name="orders[phone]" class="form-control" required="required" placeholder="phone" value="{{ app.user.phone }}">
    </div>

    <div class="form-group col-md-12">
        <p>KREDİ KARTI:</p>
    </div>
    <label class="col-md-12 control-label"> Adı Soyadı :</label>
    <div class="form-group col-md-12">
        <input type="text" name="cardholdername" class="form-control" required="required" placeholder="Kart adı soyadı">
    </div>
    <label class="col-md-12 control-label"> Kart Numarası :</label>
    <div class="form-group col-md-12">
        <input type="text" name="cardnumber" class="form-control" required="required" placeholder="Kart Numarası">
    </div>
    <label class="col-md-12 control-label"> Son Kullanma Tarihi :</label>
    <div class="form-group col-md-12">
        <input type="text" name="cardvaliddates" class="form-control" required="required" placeholder="AY/YIL">
    </div>
    <label class="col-md-12 control-label"> Güvenlik Kodu :</label>
    <div class="form-group col-md-12">
        <input type="number" name="cardsecuritycode" class="form-control" required="required" placeholder="Güvenlik Kodu">
    </div>
    <input type="hidden" name="token" value="{{ csrf_token('form-order') }}"/>
    <label class="col-md-6 control-label"> </label>
    <div class="form-group col-md-12">
        <input type="submit" name="submit" class="btn btn-primary pull-right" value="SATIN AL">
    </div>
</form>

templates/orders/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Orders{% endblock %}

{% block body %}
    <h1>Edit Orders</h1>

    {{ include('orders/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('orders_index') }}">back to list</a>

    {{ include('orders/_delete_form.html.twig') }}
{% endblock %}

templates/orders/index.html.twig
{% extends 'blankbase.html.twig' %}

{% block title %}Orders List{% endblock %}

{% block body %}
<div class="container">
    <div class="row">

        {{ include('user/usermenu.html.twig') }}

        <div class="blog-post-area">
            <h2 class="title text-center">Orders List</h2>
            <div class="single-blog-post">

                <div class="blog-post-area">
                    <div class="row">
                        <div class="col-sm-6">
    <table class="table">
        <thead>
            <tr>

                <th>Amount</th>
                <th>Name</th>

                <th>City</th>
                <th>Phone</th>
                <th>Shipinfo</th>
                <th>Status</th>
                <th>Note</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for order in orders %}
            <tr>

                <td>{{ order.amount }}</td>
                <td>{{ order.name }}</td>

                <td>{{ order.city }}</td>
                <td>{{ order.phone }}</td>
                <td>{{ order.shipinfo }}</td>
                <td>{{ order.status }}</td>
                <td>{{ order.note }}</td>

                <td>
                    <a href="{{ path('orders_show', {'id': order.id}) }}">show</a>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="13">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
                        </div></div></div> </div></div></div>

{% endblock %}

templates/orders/new.html.twig
{% extends 'blankbase.html.twig' %}

{% block title %}Shopcart Order Items{% endblock %}

{% block body %}
<div class="container">
    <div class="row">

        {{ include('user/usermenu.html.twig') }}

        <div class="blog-post-area">

            <div class="single-blog-post">

                <div class="blog-post-area">
                    <div class="row">
                        <div class="col-sm-6">

                            {{ include('orders/_form.html.twig') }}

                            <a href="{{ path('orders_index') }}">back to list</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

templates/orders/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Orders{% endblock %}

{% block body %}
    <h1>Orders</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ order.id }}</td>
            </tr>
            <tr>
                <th>Userid</th>
                <td>{{ order.userid }}</td>
            </tr>
            <tr>
                <th>Amount</th>
                <td>{{ order.amount }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ order.name }}</td>
            </tr>
            <tr>
                <th>Adress</th>
                <td>{{ order.adress }}</td>
            </tr>
            <tr>
                <th>City</th>
                <td>{{ order.city }}</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>{{ order.phone }}</td>
            </tr>
            <tr>
                <th>Shipinfo</th>
                <td>{{ order.shipinfo }}</td>
            </tr>
            <tr>
                <th>Status</th>
                <td>{{ order.status }}</td>
            </tr>
            <tr>
                <th>Note</th>
                <td>{{ order.note }}</td>
            </tr>
            <tr>
                <th>Updated_at</th>
                <td>{{ order.updatedAt ? order.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Created_at</th>
                <td>{{ order.createdAt ? order.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('orders_index') }}">back to list</a>

    <a href="{{ path('orders_edit', {'id': order.id}) }}">edit</a>

    {{ include('orders/_delete_form.html.twig') }}
    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Orderid</th>
            <th>Userid</th>
            <th>Siparisid</th>
            <th>Price</th>
            <th>Quantity</th>
            <th>Amount</th>
            <th>Name</th>
            <th>Status</th>
            <th>actions</th>
        </tr>
        </thead>
        <tbody>
        {% for rs in orderdetail %}
            <tr>
                <td>{{ rs.id }}</td>
                <td>{{ rs.orderid }}</td>
                <td>{{ rs.userid }}</td>
                <td>{{ rs.siparisid }}</td>
                <td>{{ rs.price }}</td>
                <td>{{ rs.quantity }}</td>
                <td>{{ rs.amount }}</td>
                <td>{{ rs.name }}</td>
                <td>{{ rs.status }}</td>

            </tr>
        {% else %}
            <tr>
                <td colspan="10">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}